# Generated by Django 6.1 on 2026-10-02 17:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(help_text='e.g. Municipal Health Officer, Barangay Kagawad', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Format: +639123456789', max_length=25)),
                ('barangay_filter', models.CharField(blank=True, help_text='Barangay name to filter alerts for, or leave blank to receive alerts for all barangays', max_length=100)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_sms', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('FLOAT', 'Float')], default='STRING', max_length=10)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('HEALTH_OFFICER', 'Health Officer / LGU Official'), ('ENGINEER', 'Sanitation Engineer'), ('RESIDENT', 'Resident')], default='RESIDENT', help_text='Role determining system permissions', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='e.g. +63 912 345 6789', max_length=25)),
                ('barangay', models.CharField(blank=True, help_text='Assigned or residential barangay', max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text='Official Staff/LGU ID', max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning (Caution Level)'), ('CRITICAL', 'Critical (Unsafe Contamination)')], default='CRITICAL', max_length=20)),
                ('summary', models.TextField(help_text='Summary of violated water parameters')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Actions taken to remediate water source (e.g. shock chlorination, re-testing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('destination', models.CharField(help_text='Email address or phone number', max_length=150)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('MOCKED', 'Simulated (Mock/Console Mode)')], max_length=10)),
                ('message_content', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.alert')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(help_text="Identifier: 'ph', 'turbidity', 'tds'", max_length=30, unique=True)),
                ('parameter_name', models.CharField(help_text="Display name: e.g. 'pH Level'", max_length=100)),
                ('unit', models.CharField(help_text='Measurement unit (e.g., pH, NTU, mg/L)', max_length=20)),
                ('min_safe', models.DecimalField(blank=True, decimal_places=2, help_text='Lower limit (inclusive)', max_digits=8, null=True)),
                ('max_safe', models.DecimalField(blank=True, decimal_places=2, help_text='Upper limit (inclusive)', max_digits=8, null=True)),
                ('caution_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage proximity to limit that triggers CAUTION status (e.g. 10%)', max_digits=5)),
                ('standard_reference', models.CharField(default='PNSDW 2017 / WHO Guidelines', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Health effects or significance of this parameter')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parameter_code'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(help_text='Date and time water sample was tested')),
                ('ph_level', models.DecimalField(decimal_places=2, help_text='pH Level (0.00 - 14.00)', max_digits=5)),
                ('turbidity_ntu', models.DecimalField(decimal_places=2, help_text='Turbidity in Nephelometric Turbidity Units (NTU)', max_digits=7)),
                ('tds_ppm', models.DecimalField(decimal_places=2, help_text='Total Dissolved Solids in mg/L (ppm)', max_digits=8)),
                ('overall_status', models.CharField(choices=[('SAFE', 'Safe'), ('CAUTION', 'Caution'), ('UNSAFE', 'Unsafe')], default='SAFE', help_text='Calculated overall safety status', max_length=15)),
                ('failed_parameters', models.JSONField(blank=True, default=list, help_text='List of parameter codes and explanations that violated safe or caution limits')),
                ('notes', models.TextField(blank=True, help_text='Field technician notes, weather conditions, or observations')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records', to=settings.AUTH_USER_MODEL)),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.waterqualityrecord'),
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique source identifier, e.g., WELL-BARANGAY-01', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name (e.g., Purok 3 Communal Well)', max_length=150)),
                ('source_type', models.CharField(choices=[('DEEP_WELL', 'Communal Deep Well'), ('SHALLOW_WELL', 'Shallow Tube Well'), ('SPRING', 'Natural Spring Box'), ('COMMUNAL_TAP', 'Public Communal Tap Stand'), ('REFILLING_STATION', 'Local Water Refilling Station')], default='DEEP_WELL', max_length=30)),
                ('barangay', models.CharField(help_text='Barangay / village name', max_length=100)),
                ('address_details', models.TextField(blank=True, help_text='Landmark or exact location notes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Optional GPS Latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Optional GPS Longitude', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active for regular water sampling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, help_text='Sanitation Engineer assigned to monitor this source', limit_choices_to={'role': 'ENGINEER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['barangay', 'name'],
            },
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.watersource'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.watersource'),
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Boil Water Notice for Purok 2 Residents', max_length=200)),
                ('advisory_type', models.CharField(choices=[('BOIL_WATER', 'Boil Water Advisory'), ('CONTAMINATION_ALERT', 'Water Contamination Warning'), ('MAINTENANCE', 'System Maintenance & Flushing'), ('CLEARANCE', 'Safety Clearance / Advisory Lifted')], default='BOIL_WATER', max_length=30)),
                ('barangay', models.CharField(blank=True, help_text='Specific barangay or leave blank for municipality-wide', max_length=100)),
                ('summary', models.TextField(help_text='Plain language description of the water quality advisory')),
                ('instructions', models.TextField(help_text='Actionable instructions for residents (e.g. boil water for at least 3 minutes, use designated alternate station)')),
                ('is_active', models.BooleanField(default=True, help_text='Visible on the public portal')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date/time', null=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_advisories', to=settings.AUTH_USER_MODEL)),
                ('affected_sources', models.ManyToManyField(blank=True, related_name='advisories', to='core.watersource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(help_text='e.g. USER_LOGIN, RECORD_CREATE, THRESHOLD_UPDATE', max_length=100)),
                ('module', models.CharField(help_text='e.g. AUTH, WATER_RECORDS, THRESHOLDS, ALERTS', max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='core_auditl_module_24bec6_idx'), models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='watersource',
            index=models.Index(fields=['barangay', 'is_active'], name='core_waters_baranga_25db87_idx'),
        ),
        migrations.AddIndex(
            model_name='watersource',
            index=models.Index(fields=['code'], name='core_waters_code_fc7cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='waterqualityrecord',
            index=models.Index(fields=['source', 'tested_at'], name='core_waterq_source__d52e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='waterqualityrecord',
            index=models.Index(fields=['overall_status', 'is_deleted'], name='core_waterq_overall_452613_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='core_alert_status_9f08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source', 'status'], name='core_alert_source__e97572_idx'),
        ),
    ]
